### PR TITLE
Read config from file

### LINKED ISSUE #126: reg server - read config from config file
It would be awesome if the reg ui server could read its config from a file, since it requires credentials for authentication against the docker registry which might are visible by examining the process.

### PR DESCRIPTION
**Pull request by mrueg**
Decided for implementing it without replacing the cli library.

This resolves what I need in https://github.com/genuinetools/reg/issues/126 but replacing the cli lib might be a better option.

Fixes: https://github.com/genuinetools/reg/issues/126

### CODE REVIEW

**Comment by ulm0** [comment]
i just made a [docker image](https://github.com/ulm0/dockerfiles/tree/master/reg) for `reg server ...` only, and had to *partially* verify some settings using env vars, passing a config file is going to be really helpful

**Comment by mrueg** [comment]
@jessfraz if your time permits, can you take a look and agree with the general direction? I'll fix up the merge conflict then.

**Comment by jessfraz** [comment]
lgtm, can we make the flag `--config` thanks :)

**Comment by mrueg** [comment]
@jessfraz thanks for the feedback. Applied it and switched to go module vendoring.

**Comment by mrueg** [comment]
Rebased on master, tests don't fail anymore

**Comment by mrueg** [comment]
@jessfraz can I bother you to take another look? Thanks :)

**Comment by mrueg** [comment]
@jessfraz friendly ping on this one

**Comment by williamh** [comment]
*friendly ping*

**Pull request closed without merging**
