### PR TITLE
Insecure transport

### LINKED ISSUE #76: Use of `-k` fails on registry.token
When adding the `-k` flag for `reg vulns` the code that does a GET for the registry token doesn't use the HTTP transport in the Registry object.  This causing errors even when passing `-k`

```
/ # reg -k -r https://toolchain-docker-registry:5000 -d vulns --clair http://toolchain-clair:6060 hello-helm:bb5c83266423c9df1be4167d6a37d670fcfbeb7c
2018/03/03 00:04:54 registry.ping url=https://toolchain-docker-registry:5000/v2/
2018/03/03 00:04:54 registry.manifests uri=https://toolchain-docker-registry:5000/v2/hello-helm/manifests/bb5c83266423c9df1be4167d6a37d670fcfbeb7c repository=hello-helm ref=bb5c83266423c9df1be4167d6a37d670fcfbeb7c
2018/03/03 00:04:54 registry.registry resp.Status=200 OK
DEBU[0000] 0: layer={sha256:8a9dd1217d249766a7531546fabd659da4cebcccf9bd97ba213c6fd0baa7fbe1} <-- append
DEBU[0000] 1: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 2: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 3: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 4: layer={sha256:46896e703a67aa57edeb7ee41bb624de538d5d41c0d4f95fa303ef437b9dc1e5} <-- append
DEBU[0000] 5: layer={sha256:1bd100b85ae7c9647877ddce75e965bc1d1823836acebe40d803fbb44c6baba2} <-- append
DEBU[0000] 6: layer={sha256:4ebb41998934f28008092c9c058617dae4ac0419589183305478f8b23dfcc46c} <-- append
DEBU[0000] 7: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 8: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 9: layer={sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4}
DEBU[0000] 10: layer={sha256:128191993b8a5e9d949346160926359ad02df93bde62f5af8a7bc3573f53553e} <-- append
Analysing 5 layers
2018/03/03 00:04:54 registry.token url=https://toolchain-docker-registry:5000/v2/hello-helm/blobs/sha256:128191993b8a5e9d949346160926359ad02df93bde62f5af8a7bc3573f53553e
FATA[0000] Get https://toolchain-docker-registry:5000/v2/hello-helm/blobs/sha256:128191993b8a5e9d949346160926359ad02df93bde62f5af8a7bc3573f53553e: x509: certificate signed by unknown authority
```

### PR DESCRIPTION
**Pull request by cplee**
Fix #76 

(also includes PR #75)

### CODE REVIEW

**Comment by cplee** [comment]
ugh...didn't notice that #75 was failed in travis.

**Comment by jessfraz** [comment]
thanks for this! sorry to be a pain but can it not include the version file fix, i need to do that for all my makefiles and havent decided how i want to do it yet but i have a whole "update all the repos with new makefiles" script this will break

**Comment by cplee** [comment]
@jessfraz no worries...i've made that update.

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
