### PR TITLE
Add --auth-url parameter

### LINKED ISSUE #90: Proposal: Add --auth-url parameter
In some registries, like gitlab which uses registry v2, authentication might be done in a different url than the registry url. Example from docker distribution docs:
https://docs.docker.com/registry/spec/auth/jwt/

repos are under docker.io/namespace/repo and authentication is done with auth.docker.io.

My organizations private gitlab registry is using something similar.

### PR DESCRIPTION
**Pull request by azillion**
Initial work for #90 
closes #90 
I don't have a way of testing this though.

### CODE REVIEW

**Comment by azillion** [comment]
Will update this PR. Still not sure how to test it though

**Comment by jessfraz** [comment]
thanks!!! @strigazi do you want to test this with your setup?

**Comment by azillion** [comment]
I'll stand up a gitlab instance to see if I can test this myself

**Comment by jessfraz** [comment]
thanks so much just want to make sure it works :)
On Wed, Sep 5, 2018 at 3:10 PM alexander zillion
<notifications@github.com> wrote:
>
> I'll stand up a gitlab instance to see if I can test this myself
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu

**Comment by strigazi** [comment]
My apologies, I missed this, I'll test it today.

**Comment by azillion** [comment]
@strigazi no problem, unfortunately this PR needs updated. I can try to have that done by tomorrow for you to test though

**Comment by strigazi** [comment]
@azillion have you rebased your patch?

**Comment by strigazi** [comment]
I tested with feat/auth-url and the parameter works fine. However, our gitlab deployment is updated and I can not reproduce the scenario that didn't work before. I'll try to generate a scenario that it doesn't work without --auth-url.

As for the proposed patch, looks good to me.

**Comment by azillion** [comment]
Sorry for the delay, updated the PR.

**Comment by azillion** [comment]
@strigazi Could you give this another test?

**Comment by strigazi** [comment]
sure

**Comment by strigazi** [comment]
@jessfraz @azillion  LGTM

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
