### PR TITLE
Fix vulnerability scanning on GCR

### PR DESCRIPTION
**Pull request by Luzifer**
This proposal does the trick to get the vulnerability scanning to work with private GCR hosted images. Though this feels like a quite ugly hack (checking for string matching), so in case you know a better place for this or a better method of checking I'd be happy to change the code…

### CODE REVIEW

**Comment by jessfraz** [comment]
do you think we can add a test with one of the public images :)

**Comment by jessfraz** [comment]
thanks so much for this!

**Comment by Luzifer** [comment]
Sadly the public images are working without any issue without this patch… You would need a project with a private registry just to have a test for this… 😞

**Comment by jessfraz** [comment]
Okay thanks!!

**Pull request merged**
