### PR TITLE
support 'access_token' for compatibility with OAuth 2.0  https://docs…

### PR DESCRIPTION
**Pull request by jamierobertsusa**
….docker.com/registry/spec/auth/token/#requesting-a-token

### CODE REVIEW

**Comment by jessfraz** [comment]
thanks!

**Comment by jessfraz** [comment]
do you know what registries use this protocol would be nice to have it documented somewhere :)

**Comment by carlpett** [comment]
I _think_ Azure Container Registries? Currently I get this when using `reg` with ACR:

```
$ reg ls our-registry.azurecr.io
Get https://our-registry.azurecr.io/v2/: unknown field in challege header error: Bearer realm="https://our-registry.azurecr.io/oauth2/token",service="our-registry.azurecr.io",error="malformed_token"
```

Although, this PR seems to have `access_token`, while my .docker/config.json has `identitytoken`. So maybe not?

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
