### PR TITLE
Fix GCR errors

### PR DESCRIPTION
**Pull request by tomoyamachi**
# What did you implement:

- Fix `make test` error
- Fix fetch GCR manifests error
- Update go.sum

# How Has This Been Tested?

- run `make dtest`
- run `reg manifest` to GCR repository
- run `reg manifest` to Docker repository
- run `reg manifest` to ECR repository

# Description

## Fix `make test` error

Currently "*.gcr.io/v2/" don't support ping even if users have auth tokens.
```
$ curl -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://gcr.io/v2/"
{"errors":[{"code":"UNAUTHORIZED","message":"Unauthorized access."}]}%

$ curl -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://gcr.io/project/repo/manifests/tag"
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
...

// valid auth token
```

This error has been occurring since 2 months ago on Travis-CI.
https://travis-ci.org/genuinetools/reg/jobs/496258846
https://travis-ci.org/genuinetools/reg/jobs/496787700

## Fix fetch GCR manifests error
https://github.com/genuinetools/reg/issues/137

GCR only accept Qvalue=1(default value).
I deleted Q value on an Accept header because I can't find why this project using q=0.9.

```
// fail
$ curl GET -sL -H "Accept: application/vnd.docker.distribution.manifest.v2+json;q=0.9" -H "Authorization: Bearer $TOKEN" "https://gcr.io/v2/project/repository/manifests/tag"
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"Manifest with tag 'latest' has media type 'application/vnd.docker.distribution.manifest.v2+json', but client accepts 'application/vnd.docker.distribution.manifest.v2+json;q=0.9'."}]}% 

// success
$ curl GET -sL -H "Accept: application/vnd.docker.distribution.manifest.v2+json;q=1" -H "Authorization: Bearer $TOKEN" "https://gcr.io/v2/project/repository/manifests/tag"
$ curl GET -sL -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $TOKEN" "https://gcr.io/v2/project/repository/manifests/tag"
```

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Found some fixes!

_P.S. share your ideas, feedbacks or issues with us at https://github.com/fixmie/feedback (this message will be removed after the beta stage)._

**Comment by tomoyamachi** [comment]
@jessfraz Hello. I’d love your feedback. Thanks

**Comment by jessfraz** [comment]
thanks!!

**Comment by jaswdr** [comment]
@tomoyamachi I have the same problems with GCR, those accept headers you commented were introduced in #130, thanks for this PR, I can now use GCR again :+1:

**Pull request merged**
